/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int __cdecl sub_10001000(int a1, int a2);
char __cdecl sub_10001060(int a1);
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved);
unsigned int __stdcall V2Link(int a1);
_DWORD __stdcall V2Unlink(); // idb
char sub_10001170();
char sub_10001230();
_DWORD nullsub_1(); // weak
void __thiscall sub_10001241(struct type_info *this);
void *__thiscall sub_10001251(void *this, char a2);
// void __cdecl operator delete(void *); idb
// void __cdecl type_info::_Type_info_dtor(struct type_info *); idb
// _DWORD __cdecl _encode_pointer(_DWORD); weak
// int _encoded_null(void); weak
// _DWORD __cdecl _decode_pointer(_DWORD); weak
int __cdecl sub_1000232E(int a1);
// void __cdecl free(void *Block);
std::exception *__thiscall sub_100024D1(std::exception *this, char *a2);
void __thiscall sub_100024EF(void *this);
void *__thiscall sub_100024FA(void *this, char a2);
std::exception *__thiscall sub_10003087(std::exception *this, struct std::exception *a2);
void *sub_10003D6A();
void __cdecl sub_10003D90(); // idb
int __cdecl sub_10004262(int a1);
int sub_100049AF();
int __cdecl sub_10004B6C(int a1, int a2, int a3);
void sub_10006411();
// _DWORD __thiscall std::exception::exception(std::exception *__hidden this, const char *const *); idb
// _DWORD __thiscall std::exception::exception(std::exception *__hidden this, const struct std::exception *); idb
void __thiscall sub_100064C9(void *this);
void *__thiscall sub_100064EC(void *this, char a2);
int __cdecl sub_10006FED(int a1);
int __cdecl sub_10006FFC(int a1);
int __cdecl sub_1000706B(int a1);
// int _get_sse2_info(void); weak
int sub_10007702();
// FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
// HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName);

//-------------------------------------------------------------------------
// Data declarations

void *type_info::`vftable' = &sub_10001251; // weak
void *std::bad_exception::`vftable' = &sub_100024FA; // weak
void *std::exception::`vftable' = &sub_100064EC; // weak
_UNKNOWN unk_1000ABE0; // weak
char aTtjsstringTtjs_0[27] = "tTJSString::~ tTJSString()"; // weak
char *off_1000C04C = "void ::TVPMIDIOutData(const tjs_uint8 *,int)"; // weak
char aTtjsstringTtjs[41] = "tTJSString::tTJSString(const tjs_char *)"; // weak
char aVoidTvpsetcomm[57] = "void ::TVPSetCommandLine(const tjs_char *,const ttstr &)"; // weak
int dword_1000CD80 = 0; // weak
int dword_1000CD84 = 0; // weak
int dword_1000CF78; // weak
int dword_1000CF98; // weak
int dword_1000D2D4; // weak
int dword_1000D79C; // weak
int dword_1000D7A0; // weak
char byte_1000D7A4; // weak
int dword_1000DAF4; // weak
int dword_1000DF68; // weak
int dword_1000E104; // weak
int dword_1000E110; // weak
int dword_1000E114; // weak
int dword_1000E118; // weak
int dword_1000E11C; // weak
int dword_1000E120; // weak
int dword_1000E168; // weak
int dword_1000E16C; // weak
int dword_1000E170; // weak
int dword_1000E240; // weak
int dword_1000E244; // weak


//----- (10001000) --------------------------------------------------------
int __cdecl sub_10001000(int a1, int a2)
{
  int v2; // ecx
  int v4; // [esp+4h] [ebp-4h] BYREF
  void (*retaddr)(void); // [esp+8h] [ebp+0h]

  v4 = v2;
  if ( !(*(unsigned __int8 (__cdecl **)(int, int *, int *, int))(*(_DWORD *)dword_1000CD84 + 4))(
          dword_1000CD84,
          &a1,
          &v4,
          1) )
  {
    if ( !(*(unsigned __int8 (__stdcall **)(int))(*(_DWORD *)dword_1000CD84 + 4))(dword_1000CD84) )
      MEMORY[0] = 0;
    v4 = a2;
    retaddr();
  }
  return v4;
}
// 10001000: variable 'v2' is possibly undefined
// 1000CD84: using guessed type int dword_1000CD84;

//----- (10001060) --------------------------------------------------------
char __cdecl sub_10001060(int a1)
{
  dword_1000CD84 = a1;
  return 1;
}
// 1000CD84: using guessed type int dword_1000CD84;

//----- (100010A0) --------------------------------------------------------
BOOL __stdcall DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
  BOOL result; // eax

  result = 1;
  if ( fdwReason == 1 )
    dword_1000D79C = (int)hinstDLL;
  return result;
}
// 1000D79C: using guessed type int dword_1000D79C;

//----- (100010C0) --------------------------------------------------------
unsigned int __stdcall V2Link(int a1)
{
  int v1; // esi

  v1 = a1;
  byte_1000D7A4 = (*(unsigned __int8 (__cdecl **)(int, char **, int *, int))(*(_DWORD *)a1 + 4))(
                    a1,
                    &off_1000C04C,
                    &a1,
                    1) == 0;
  sub_10001060(v1);
  if ( !sub_10001170() )
    return 0x80004005;
  dword_1000D7A0 = dword_1000CD80;
  return 0;
}
// 1000C04C: using guessed type char *off_1000C04C;
// 1000CD80: using guessed type int dword_1000CD80;
// 1000D7A0: using guessed type int dword_1000D7A0;
// 1000D7A4: using guessed type char byte_1000D7A4;

//----- (10001110) --------------------------------------------------------
#error "1000111E: call analysis failed (funcsize=27)"

//----- (10001170) --------------------------------------------------------
char sub_10001170()
{
  void (__stdcall *v0)(char *, const wchar_t *); // eax
  void (__stdcall *v1)(const wchar_t *, char *); // eax
  void (__stdcall *v2)(char *); // eax
  int v4; // [esp+Ch] [ebp-14h]
  char v5[4]; // [esp+10h] [ebp-10h] BYREF
  int v6; // [esp+1Ch] [ebp-4h]

  v0 = (void (__stdcall *)(char *, const wchar_t *))dword_1000CF78;
  if ( !dword_1000CF78 )
  {
    v0 = (void (__stdcall *)(char *, const wchar_t *))sub_10001000((int)aTtjsstringTtjs, v4);
    dword_1000CF78 = (int)v0;
  }
  v0(v5, L"no");
  v1 = (void (__stdcall *)(const wchar_t *, char *))dword_1000D2D4;
  v6 = 0;
  if ( !dword_1000D2D4 )
  {
    v1 = (void (__stdcall *)(const wchar_t *, char *))sub_10001000((int)aVoidTvpsetcomm, v4);
    dword_1000D2D4 = (int)v1;
  }
  v1(L"-debugwin", v5);
  v2 = (void (__stdcall *)(char *))dword_1000CF98;
  v6 = 0xFFFFFFFF;
  if ( !dword_1000CF98 )
  {
    v2 = (void (__stdcall *)(char *))sub_10001000((int)aTtjsstringTtjs_0, v4);
    dword_1000CF98 = (int)v2;
  }
  v2(v5);
  return 1;
}
// 1000119F: variable 'v4' is possibly undefined
// 10009188: using guessed type wchar_t aDebugwin[10];
// 100091B0: using guessed type wchar_t aNo[3];
// 1000CF78: using guessed type int dword_1000CF78;
// 1000CF98: using guessed type int dword_1000CF98;
// 1000D2D4: using guessed type int dword_1000D2D4;

//----- (10001230) --------------------------------------------------------
char sub_10001230()
{
  return 1;
}

//----- (10001241) --------------------------------------------------------
void __thiscall sub_10001241(struct type_info *this)
{
  *(_DWORD *)this = &type_info::`vftable';
  type_info::_Type_info_dtor(this);
}
// 100091D4: using guessed type void *type_info::`vftable';

//----- (10001251) --------------------------------------------------------
void *__thiscall sub_10001251(void *this, char a2)
{
  sub_10001241((struct type_info *)this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (1000232E) --------------------------------------------------------
int __cdecl sub_1000232E(int a1)
{
  int result; // eax

  result = a1;
  dword_1000DAF4 = a1;
  return result;
}
// 1000DAF4: using guessed type int dword_1000DAF4;

//----- (100024D1) --------------------------------------------------------
std::exception *__thiscall sub_100024D1(std::exception *this, char *a2)
{
  std::exception::exception(this, (const char *const *)&a2);
  *(_DWORD *)this = &std::bad_exception::`vftable';
  return this;
}
// 10009834: using guessed type void *std::bad_exception::`vftable';

//----- (100024EF) --------------------------------------------------------
void __thiscall sub_100024EF(void *this)
{
  *(_DWORD *)this = &std::bad_exception::`vftable';
  sub_100064C9(this);
}
// 10009834: using guessed type void *std::bad_exception::`vftable';

//----- (100024FA) --------------------------------------------------------
void *__thiscall sub_100024FA(void *this, char a2)
{
  *(_DWORD *)this = &std::bad_exception::`vftable';
  sub_100064C9(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}
// 10009834: using guessed type void *std::bad_exception::`vftable';

//----- (10003087) --------------------------------------------------------
std::exception *__thiscall sub_10003087(std::exception *this, struct std::exception *a2)
{
  std::exception::exception(this, a2);
  *(_DWORD *)this = &std::bad_exception::`vftable';
  return this;
}
// 10009834: using guessed type void *std::bad_exception::`vftable';

//----- (10003D6A) --------------------------------------------------------
void *sub_10003D6A()
{
  return &unk_1000ABE0;
}

//----- (10003D90) --------------------------------------------------------
void __cdecl sub_10003D90()
{
  ;
}

//----- (10004262) --------------------------------------------------------
int __cdecl sub_10004262(int a1)
{
  int result; // eax

  result = a1;
  dword_1000DF68 = a1;
  return result;
}
// 1000DF68: using guessed type int dword_1000DF68;

//----- (100049AF) --------------------------------------------------------
int sub_100049AF()
{
  return _decode_pointer(dword_1000E104);
}
// 10001D9E: using guessed type _DWORD __cdecl _decode_pointer(_DWORD);
// 1000E104: using guessed type int dword_1000E104;

//----- (10004B6C) --------------------------------------------------------
int __cdecl sub_10004B6C(int a1, int a2, int a3)
{
  int v3; // ebx
  HMODULE v4; // eax
  HMODULE v5; // edi
  int (__stdcall *MessageBoxA)(HWND, LPCSTR, LPCSTR, UINT); // eax
  HWND (__stdcall *GetActiveWindow)(); // eax
  HWND (__stdcall *GetLastActivePopup)(HWND); // eax
  BOOL (__stdcall *GetUserObjectInformationA)(HANDLE, int, PVOID, DWORD, LPDWORD); // eax
  HWINSTA (__stdcall *GetProcessWindowStation)(); // eax
  int (*v11)(void); // esi
  int (__stdcall *v12)(int, int, char *, int, char *); // eax
  int (__stdcall *v13)(int, int, char *, int, char *); // edi
  int v14; // eax
  int (*v15)(void); // eax
  int (__stdcall *v16)(int); // eax
  int (__stdcall *v17)(int, int, int, int); // eax
  char v19[12]; // [esp+10h] [ebp-14h] BYREF
  char v20[4]; // [esp+1Ch] [ebp-8h] BYREF
  int v21; // [esp+20h] [ebp-4h]

  v21 = 0;
  v3 = _encoded_null();
  if ( !dword_1000E110 )
  {
    v4 = LoadLibraryA("USER32.DLL");
    v5 = v4;
    if ( !v4 )
      return 0;
    MessageBoxA = (int (__stdcall *)(HWND, LPCSTR, LPCSTR, UINT))GetProcAddress(v4, "MessageBoxA");
    if ( !MessageBoxA )
      return 0;
    dword_1000E110 = _encode_pointer(MessageBoxA);
    GetActiveWindow = (HWND (__stdcall *)())GetProcAddress(v5, "GetActiveWindow");
    dword_1000E114 = _encode_pointer(GetActiveWindow);
    GetLastActivePopup = (HWND (__stdcall *)(HWND))GetProcAddress(v5, "GetLastActivePopup");
    dword_1000E118 = _encode_pointer(GetLastActivePopup);
    GetUserObjectInformationA = (BOOL (__stdcall *)(HANDLE, int, PVOID, DWORD, LPDWORD))GetProcAddress(
                                                                                          v5,
                                                                                          "GetUserObjectInformationA");
    dword_1000E120 = _encode_pointer(GetUserObjectInformationA);
    if ( dword_1000E120 )
    {
      GetProcessWindowStation = (HWINSTA (__stdcall *)())GetProcAddress(v5, "GetProcessWindowStation");
      dword_1000E11C = _encode_pointer(GetProcessWindowStation);
    }
  }
  if ( dword_1000E11C == v3
    || dword_1000E120 == v3
    || (v11 = (int (*)(void))_decode_pointer(dword_1000E11C),
        v12 = (int (__stdcall *)(int, int, char *, int, char *))_decode_pointer(dword_1000E120),
        v13 = v12,
        !v11)
    || !v12
    || (v14 = v11()) != 0 && v13(v14, 1, v19, 0xC, v20) && (v19[8] & 1) != 0 )
  {
    if ( dword_1000E114 != v3 )
    {
      v15 = (int (*)(void))_decode_pointer(dword_1000E114);
      if ( v15 )
      {
        v21 = v15();
        if ( v21 )
        {
          if ( dword_1000E118 != v3 )
          {
            v16 = (int (__stdcall *)(int))_decode_pointer(dword_1000E118);
            if ( v16 )
              v21 = v16(v21);
          }
        }
      }
    }
  }
  else
  {
    a3 |= 0x200000u;
  }
  v17 = (int (__stdcall *)(int, int, int, int))_decode_pointer(dword_1000E110);
  if ( v17 )
    return v17(v21, a1, a2, a3);
  return 0;
}
// 10001D23: using guessed type _DWORD __cdecl _encode_pointer(_DWORD);
// 10001D95: using guessed type int _encoded_null(void);
// 10001D9E: using guessed type _DWORD __cdecl _decode_pointer(_DWORD);
// 1000E110: using guessed type int dword_1000E110;
// 1000E114: using guessed type int dword_1000E114;
// 1000E118: using guessed type int dword_1000E118;
// 1000E11C: using guessed type int dword_1000E11C;
// 1000E120: using guessed type int dword_1000E120;

//----- (10006411) --------------------------------------------------------
void sub_10006411()
{
  dword_1000E244 = 0;
}
// 1000E244: using guessed type int dword_1000E244;

//----- (100064C9) --------------------------------------------------------
void __thiscall sub_100064C9(void *this)
{
  bool v1; // zf

  v1 = *((_DWORD *)this + 2) == 0;
  *(_DWORD *)this = &std::exception::`vftable';
  if ( !v1 )
    free(*((void **)this + 1));
}
// 1000A104: using guessed type void *std::exception::`vftable';

//----- (100064EC) --------------------------------------------------------
void *__thiscall sub_100064EC(void *this, char a2)
{
  sub_100064C9(this);
  if ( (a2 & 1) != 0 )
    operator delete(this);
  return this;
}

//----- (10006FED) --------------------------------------------------------
int __cdecl sub_10006FED(int a1)
{
  int result; // eax

  result = a1;
  dword_1000E168 = a1;
  return result;
}
// 1000E168: using guessed type int dword_1000E168;

//----- (10006FFC) --------------------------------------------------------
int __cdecl sub_10006FFC(int a1)
{
  int result; // eax

  result = a1;
  dword_1000E16C = a1;
  return result;
}
// 1000E16C: using guessed type int dword_1000E16C;

//----- (1000706B) --------------------------------------------------------
int __cdecl sub_1000706B(int a1)
{
  int result; // eax

  result = a1;
  dword_1000E170 = a1;
  return result;
}
// 1000E170: using guessed type int dword_1000E170;

//----- (10007702) --------------------------------------------------------
int sub_10007702()
{
  dword_1000E240 = _get_sse2_info();
  return 0;
}
// 100076A0: using guessed type int _get_sse2_info(void);
// 1000E240: using guessed type int dword_1000E240;

// nfuncs=226 queued=26 decompiled=26 lumina nreq=0 worse=0 better=0
#error "There were 1 decompilation failure(s) on 26 function(s)"
